version: "3.3"
services:
  web:
    build: .
    ports:
      - "8000:5000"
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
